# Generated by Django 4.0 on 2021-12-09 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('product', '0008_product_rating'),
        ('comment', '0003_auto_20211201_0822'),
        ('adminUser', '0002_userreport_remove_report_reporteduser_report_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userreport',
            name='reportedUser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ReportedUser', to='auth.user'),
        ),
        migrations.AlterField(
            model_name='productcommentreport',
            name='comment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='comment.productcomment'),
        ),
        migrations.AlterField(
            model_name='productreport',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.product'),
        ),
    ]
