# Generated by Django 4.0 on 2021-12-09 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0003_auto_20211201_0822'),
        ('product', '0008_product_rating'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('adminUser', '0003_userreport_reporteduser_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcommentreport',
            name='comment',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='comment.productcomment'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productreport',
            name='product',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='product.product'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userreport',
            name='reportedUser',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='ReportedUser', to='auth.user'),
            preserve_default=False,
        ),
    ]
