# Generated by Django 4.0 on 2021-12-09 14:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('adminUser', '0004_alter_productcommentreport_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
