# Generated by Django 4.0 on 2021-12-10 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0003_auto_20211201_0822'),
        ('product', '0008_product_rating'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('adminUser', '0005_report_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcommentreport',
            name='comment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='comment.productcomment'),
        ),
        migrations.AlterField(
            model_name='productreport',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.product'),
        ),
        migrations.AlterField(
            model_name='report',
            name='reportingUser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ReportingUser', to='auth.user'),
        ),
        migrations.AlterField(
            model_name='userreport',
            name='reportedUser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ReportedUser', to='auth.user'),
        ),
    ]
