# Generated by Django 3.2.9 on 2021-11-29 15:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_seller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='joinDate',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
