# Generated by Django 3.2.9 on 2021-12-01 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20211201_0524'),
        ('comment', '0002_alter_productcomment_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcomment',
            name='customer',
        ),
        migrations.AlterField(
            model_name='productcomment',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='order.order'),
        ),
    ]
