# Generated by Django 3.2.9 on 2021-12-01 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20211130_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='phoneNumber',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='orderstatus',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
