# Generated by Django 3.2.9 on 2021-12-02 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_product_category'),
        ('order', '0003_auto_20211201_0524'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
        migrations.AddField(
            model_name='order',
            name='productSpec',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.productspec'),
        ),
    ]
