# Generated by Django 3.2.9 on 2021-12-03 06:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_product_category'),
        ('order', '0006_auto_20211202_2348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='productSpec',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.productspec'),
        ),
    ]
