# Generated by Django 3.2.9 on 2021-12-03 07:50

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_alter_order_productspec'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReturnRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('incorrect product', 'incorrect product'), ('incorrect spec', 'incorrect spec'), ('product does not match description', 'product does not match description'), ('product was damaged', 'product was damaged'), ('product does not meet customer’s expectation', 'product does not meet customer’s expectation'), ('others', 'others')], default='others', max_length=50)),
                ('status', models.TextField(choices=[('pending', 'pending'), ('succesful', 'succesful'), ('failed', 'failed')], default='pending', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='order.order')),
            ],
        ),
    ]
