# Generated by Django 3.2.9 on 2021-12-07 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_returnrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderstatus',
            name='status',
            field=models.CharField(choices=[('paid', 'paid'), ('shipped', 'shipped'), ('delivered', 'delivered'), ('returning', 'returning'), ('returned', 'returned')], default='paid', max_length=100),
        ),
    ]
