# Generated by Django 4.0 on 2021-12-08 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_alter_orderstatus_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderstatus',
            name='status',
            field=models.CharField(choices=[('paid', 'paid'), ('shipped', 'shipped'), ('delivered', 'delivered'), ('returning', 'returning'), ('returned', 'returned'), ('completed', 'completed')], default='paid', max_length=100),
        ),
    ]
