# Generated by Django 4.0 on 2021-12-10 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_postman'),
        ('order', '0012_alter_orderstatus_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='postman',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.postman'),
        ),
    ]
