# Generated by Django 3.2.9 on 2021-11-30 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_seller_joindate'),
        ('product', '0002_productspec'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='seller',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='user.seller'),
        ),
        migrations.AddField(
            model_name='product',
            name='soldAmount',
            field=models.IntegerField(default=0),
        ),
    ]
