# Generated by Django 3.2.9 on 2021-12-02 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_alter_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('women clothes', 'women clothes'), ('men clothes', 'men clothes'), ('sports', 'sports'), ('cosmetics', 'cosmetics'), ('drinks', 'drinks'), ('snacks', 'snacks'), ('others', 'others')], default='others', max_length=50),
        ),
    ]
